package uni_stuttgart.iaas.spi.cmp.service;

import javax.jws.WebParam;
import javax.jws.WebService;

import de.uni_stuttgart.iaas.cmp.v0.TTaskCESDefinition;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-01-21T15:37:54.425+01:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://service.cmp.spi.iaas.uni_stuttgart/", name = "CESExecutorService")
public class CESExecutorService {

	public void CESExecutor(@WebParam(name="CESDefinition") TTaskCESDefinition cesDefinitionReceived){
		uni_stuttgart.iaas.spi.cmp.realizations.CESExecutor cesExecutor = new uni_stuttgart.iaas.spi.cmp.realizations.CESExecutor(cesDefinitionReceived);
		cesExecutor.runCESExecutor();
	}
	
}
