package uni_stuttgart.iaas.spi.cmp.service;

import javax.jws.WebParam;
import javax.jws.WebService;

import de.uni_stuttgart.iaas.cmp.v0.TTaskCESDefinition;

/** 
 * Copyright 2016 Debasis Kar
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
**/

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-01-21T15:37:54.425+01:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://service.cmp.spi.iaas.uni_stuttgart/", name = "CESExecutorService")
public class CESExecutorService {

	public void CESExecutor(@WebParam(name="CESDefinition") TTaskCESDefinition cesDefinitionReceived){
		uni_stuttgart.iaas.spi.cmp.realizations.CESExecutor cesExecutor = new uni_stuttgart.iaas.spi.cmp.realizations.CESExecutor(cesDefinitionReceived);
		cesExecutor.runCESExecutor();
	}
	
}
