
package org.debasis.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.3
 * Fri Oct 09 16:35:46 CEST 2015
 * Generated source version: 3.1.3
 */

@XmlRootElement(name = "automate", namespace = "http://ws.debasis.org/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "automate", namespace = "http://ws.debasis.org/")

public class Automate {

    @XmlElement(name = "arg0")
    private java.lang.String arg0;

    public java.lang.String getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.String newArg0)  {
        this.arg0 = newArg0;
    }

}

