
package org.debasis.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.3
 * Fri Oct 09 16:35:46 CEST 2015
 * Generated source version: 3.1.3
 */

@XmlRootElement(name = "automateResponse", namespace = "http://ws.debasis.org/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "automateResponse", namespace = "http://ws.debasis.org/")

public class AutomateResponse {

    @XmlElement(name = "return")
    private java.lang.String _return;

    public java.lang.String getReturn() {
        return this._return;
    }

    public void setReturn(java.lang.String new_return)  {
        this._return = new_return;
    }

}

