
package uni_stuttgart.iaas.spi.cmp.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.4
 * Tue Feb 09 21:26:26 CET 2016
 * Generated source version: 3.1.4
 */

@XmlRootElement(name = "CESExecutorResponse", namespace = "http://service.cmp.spi.iaas.uni_stuttgart/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CESExecutorResponse", namespace = "http://service.cmp.spi.iaas.uni_stuttgart/")

public class CESExecutorResponse {


}

