package unistuttgart.iaas.spi.cmprocess.arch;

import java.util.Map;
import java.util.Set;

import unistuttgart.iaas.spi.cmprocess.cmp.TProcessSet;

public interface IContextAnalyzer {
	/*A given set of Process Definitions need to be scanned and the context expression
	 * of each process need to be calculated for the Context Data available with us.
	 * The final result is stored in a tabular form with tuples e.g. (ProcessID, True/False).
	 * True/False is based on whether the process definition is valid under the current context.*/
	public Map<String, Boolean> analyzeContext(TProcessSet processSet);
	
	/*This method scans the table generated by previous method and discards the tuples having
	 * False value. Hence it stores the Process IDs in a Set which have successfully passed the
	 * context conditions (True Value).*/
	public Set<String> getProcessListOfContextAnalyzer(Map<String, Boolean> contextAnalyzerProcessTable);
}
