package unistuttgart.iaas.spi.cmprocess.arch;

import java.util.Set;

import unistuttgart.iaas.spi.cmprocess.cmp.TIntention;
import unistuttgart.iaas.spi.cmprocess.cmp.TProcessSet;

public interface IIntentionAnalyzer {
	/*A given set of Process Definitions need to be scanned, and the main and sub-intentions
	 * of each process need to be matched with the data available with us. The final result 
	 * of matching process list is stored in a Set data structure.*/
	public Set<String> analyzeIntention(TProcessSet processSet, TIntention mainIntention);
	
	/*This method scans the list generated by previous method and intersects it with the process
	 * identifiers received from Context Analyzer. Final list is stored in a Set data structure which 
	 * is then forwarded to ProcessOptimizer for Weight and Optimization Analysis.*/
	public Set<String> getProcessListOfIntentionAnalyzer(Set<String> processesFromContextAnalyzer);
}
