
package org.debasis.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Fri Feb 05 00:24:51 CET 2016
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "automate", namespace = "http://service.cmp.spi.iaas.uni_stuttgart/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "automate", namespace = "http://service.cmp.spi.iaas.uni_stuttgart/")

public class Automate {

    @XmlElement(name = "task")
    private java.lang.String task;

    public java.lang.String getTask() {
        return this.task;
    }

    public void setTask(java.lang.String newTask)  {
        this.task = newTask;
    }

}

