
package org.debasis.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Fri Feb 05 00:24:51 CET 2016
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "automateResponse", namespace = "http://service.cmp.spi.iaas.uni_stuttgart/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "automateResponse", namespace = "http://service.cmp.spi.iaas.uni_stuttgart/")

public class AutomateResponse {

    @XmlElement(name = "return")
    private java.lang.String _return;

    public java.lang.String getReturn() {
        return this._return;
    }

    public void setReturn(java.lang.String new_return)  {
        this._return = new_return;
    }

}

