//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.15 at 03:46:13 AM CET 
//


package demo;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the demo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Documentation_QNAME = new QName("http://docs.oasis-open.org/tosca/ns/2011/12", "documentation");
    private final static QName _InformalProcessInstance_QNAME = new QName("http://www.uni-stuttgart.de/iaas/ipsm/v0.2/", "InformalProcessInstance");
    private final static QName _OrganizationalDefinitions_QNAME = new QName("http://www.uni-stuttgart.de/iaas/ipsm/v0.2/", "OrganizationalDefinitions");
    private final static QName _InformalProcessDefinition_QNAME = new QName("http://www.uni-stuttgart.de/iaas/ipsm/v0.2/", "InformalProcessDefinition");
    private final static QName _OperationMessage_QNAME = new QName("http://www.uni-stuttgart.de/iaas/ipsm/v0.2/", "OperationMessage");
    private final static QName _ProcessDefinition_QNAME = new QName("http://www.uni-stuttgart.de/iaas/ipsm/v0.2/", "ProcessDefinition");
    private final static QName _ProcessInstance_QNAME = new QName("http://www.uni-stuttgart.de/iaas/ipsm/v0.2/", "ProcessInstance");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: demo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TDefinitions }
     * 
     */
    public TDefinitions createTDefinitions() {
        return new TDefinitions();
    }

    /**
     * Create an instance of {@link TRelationshipTemplate }
     * 
     */
    public TRelationshipTemplate createTRelationshipTemplate() {
        return new TRelationshipTemplate();
    }

    /**
     * Create an instance of {@link TRelationshipTemplate.RelationshipConstraints }
     * 
     */
    public TRelationshipTemplate.RelationshipConstraints createTRelationshipTemplateRelationshipConstraints() {
        return new TRelationshipTemplate.RelationshipConstraints();
    }

    /**
     * Create an instance of {@link TRequirementDefinition }
     * 
     */
    public TRequirementDefinition createTRequirementDefinition() {
        return new TRequirementDefinition();
    }

    /**
     * Create an instance of {@link TNodeTemplate }
     * 
     */
    public TNodeTemplate createTNodeTemplate() {
        return new TNodeTemplate();
    }

    /**
     * Create an instance of {@link TTopologyElementInstanceStates }
     * 
     */
    public TTopologyElementInstanceStates createTTopologyElementInstanceStates() {
        return new TTopologyElementInstanceStates();
    }

    /**
     * Create an instance of {@link TAppliesTo }
     * 
     */
    public TAppliesTo createTAppliesTo() {
        return new TAppliesTo();
    }

    /**
     * Create an instance of {@link TImplementationArtifacts }
     * 
     */
    public TImplementationArtifacts createTImplementationArtifacts() {
        return new TImplementationArtifacts();
    }

    /**
     * Create an instance of {@link TArtifactReference }
     * 
     */
    public TArtifactReference createTArtifactReference() {
        return new TArtifactReference();
    }

    /**
     * Create an instance of {@link TBoundaryDefinitions }
     * 
     */
    public TBoundaryDefinitions createTBoundaryDefinitions() {
        return new TBoundaryDefinitions();
    }

    /**
     * Create an instance of {@link TBoundaryDefinitions.Properties }
     * 
     */
    public TBoundaryDefinitions.Properties createTBoundaryDefinitionsProperties() {
        return new TBoundaryDefinitions.Properties();
    }

    /**
     * Create an instance of {@link TExportedOperation }
     * 
     */
    public TExportedOperation createTExportedOperation() {
        return new TExportedOperation();
    }

    /**
     * Create an instance of {@link TPlan }
     * 
     */
    public TPlan createTPlan() {
        return new TPlan();
    }

    /**
     * Create an instance of {@link TCapabilityDefinition }
     * 
     */
    public TCapabilityDefinition createTCapabilityDefinition() {
        return new TCapabilityDefinition();
    }

    /**
     * Create an instance of {@link TOperation }
     * 
     */
    public TOperation createTOperation() {
        return new TOperation();
    }

    /**
     * Create an instance of {@link TArtifactTemplate }
     * 
     */
    public TArtifactTemplate createTArtifactTemplate() {
        return new TArtifactTemplate();
    }

    /**
     * Create an instance of {@link TRelationshipTypeImplementation }
     * 
     */
    public TRelationshipTypeImplementation createTRelationshipTypeImplementation() {
        return new TRelationshipTypeImplementation();
    }

    /**
     * Create an instance of {@link TRelationshipType }
     * 
     */
    public TRelationshipType createTRelationshipType() {
        return new TRelationshipType();
    }

    /**
     * Create an instance of {@link TNodeTypeImplementation }
     * 
     */
    public TNodeTypeImplementation createTNodeTypeImplementation() {
        return new TNodeTypeImplementation();
    }

    /**
     * Create an instance of {@link TNodeType }
     * 
     */
    public TNodeType createTNodeType() {
        return new TNodeType();
    }

    /**
     * Create an instance of {@link TProcessDefinition }
     * 
     */
    public TProcessDefinition createTProcessDefinition() {
        return new TProcessDefinition();
    }

    /**
     * Create an instance of {@link TInformalProcessInstance }
     * 
     */
    public TInformalProcessInstance createTInformalProcessInstance() {
        return new TInformalProcessInstance();
    }

    /**
     * Create an instance of {@link TInformalProcessDefinition }
     * 
     */
    public TInformalProcessDefinition createTInformalProcessDefinition() {
        return new TInformalProcessDefinition();
    }

    /**
     * Create an instance of {@link TOrganizationalDefinitions }
     * 
     */
    public TOrganizationalDefinitions createTOrganizationalDefinitions() {
        return new TOrganizationalDefinitions();
    }

    /**
     * Create an instance of {@link TOperationMessage }
     * 
     */
    public TOperationMessage createTOperationMessage() {
        return new TOperationMessage();
    }

    /**
     * Create an instance of {@link InstanceDescriptor }
     * 
     */
    public InstanceDescriptor createInstanceDescriptor() {
        return new InstanceDescriptor();
    }

    /**
     * Create an instance of {@link TInstanceDescriptor }
     * 
     */
    public TInstanceDescriptor createTInstanceDescriptor() {
        return new TInstanceDescriptor();
    }

    /**
     * Create an instance of {@link TProperties }
     * 
     */
    public TProperties createTProperties() {
        return new TProperties();
    }

    /**
     * Create an instance of {@link TProcessInstance }
     * 
     */
    public TProcessInstance createTProcessInstance() {
        return new TProcessInstance();
    }

    /**
     * Create an instance of {@link TCapabilityProperties }
     * 
     */
    public TCapabilityProperties createTCapabilityProperties() {
        return new TCapabilityProperties();
    }

    /**
     * Create an instance of {@link TOrganizationalProcesses }
     * 
     */
    public TOrganizationalProcesses createTOrganizationalProcesses() {
        return new TOrganizationalProcesses();
    }

    /**
     * Create an instance of {@link TIntention }
     * 
     */
    public TIntention createTIntention() {
        return new TIntention();
    }

    /**
     * Create an instance of {@link TDependencies }
     * 
     */
    public TDependencies createTDependencies() {
        return new TDependencies();
    }

    /**
     * Create an instance of {@link TOtherParameters }
     * 
     */
    public TOtherParameters createTOtherParameters() {
        return new TOtherParameters();
    }

    /**
     * Create an instance of {@link TRelationshipDefinition }
     * 
     */
    public TRelationshipDefinition createTRelationshipDefinition() {
        return new TRelationshipDefinition();
    }

    /**
     * Create an instance of {@link TResourceDefinitions }
     * 
     */
    public TResourceDefinitions createTResourceDefinitions() {
        return new TResourceDefinitions();
    }

    /**
     * Create an instance of {@link TContent }
     * 
     */
    public TContent createTContent() {
        return new TContent();
    }

    /**
     * Create an instance of {@link TOrganizationalCapability }
     * 
     */
    public TOrganizationalCapability createTOrganizationalCapability() {
        return new TOrganizationalCapability();
    }

    /**
     * Create an instance of {@link TContext }
     * 
     */
    public TContext createTContext() {
        return new TContext();
    }

    /**
     * Create an instance of {@link TRelationshipDefinitions }
     * 
     */
    public TRelationshipDefinitions createTRelationshipDefinitions() {
        return new TRelationshipDefinitions();
    }

    /**
     * Create an instance of {@link TAbstractIntentions }
     * 
     */
    public TAbstractIntentions createTAbstractIntentions() {
        return new TAbstractIntentions();
    }

    /**
     * Create an instance of {@link TResourceModel }
     * 
     */
    public TResourceModel createTResourceModel() {
        return new TResourceModel();
    }

    /**
     * Create an instance of {@link TIntentions }
     * 
     */
    public TIntentions createTIntentions() {
        return new TIntentions();
    }

    /**
     * Create an instance of {@link TConcreteIntention }
     * 
     */
    public TConcreteIntention createTConcreteIntention() {
        return new TConcreteIntention();
    }

    /**
     * Create an instance of {@link TProcessInstances }
     * 
     */
    public TProcessInstances createTProcessInstances() {
        return new TProcessInstances();
    }

    /**
     * Create an instance of {@link TResourceModelInstance }
     * 
     */
    public TResourceModelInstance createTResourceModelInstance() {
        return new TResourceModelInstance();
    }

    /**
     * Create an instance of {@link TResourceReferences }
     * 
     */
    public TResourceReferences createTResourceReferences() {
        return new TResourceReferences();
    }

    /**
     * Create an instance of {@link TContexts }
     * 
     */
    public TContexts createTContexts() {
        return new TContexts();
    }

    /**
     * Create an instance of {@link TProcessContent }
     * 
     */
    public TProcessContent createTProcessContent() {
        return new TProcessContent();
    }

    /**
     * Create an instance of {@link TConcreteIntentions }
     * 
     */
    public TConcreteIntentions createTConcreteIntentions() {
        return new TConcreteIntentions();
    }

    /**
     * Create an instance of {@link TProvidingResources }
     * 
     */
    public TProvidingResources createTProvidingResources() {
        return new TProvidingResources();
    }

    /**
     * Create an instance of {@link TResourceInstances }
     * 
     */
    public TResourceInstances createTResourceInstances() {
        return new TResourceInstances();
    }

    /**
     * Create an instance of {@link TDefinition }
     * 
     */
    public TDefinition createTDefinition() {
        return new TDefinition();
    }

    /**
     * Create an instance of {@link TStrategy }
     * 
     */
    public TStrategy createTStrategy() {
        return new TStrategy();
    }

    /**
     * Create an instance of {@link TDeploymentDescriptor }
     * 
     */
    public TDeploymentDescriptor createTDeploymentDescriptor() {
        return new TDeploymentDescriptor();
    }

    /**
     * Create an instance of {@link TOrganizationalCapabilities }
     * 
     */
    public TOrganizationalCapabilities createTOrganizationalCapabilities() {
        return new TOrganizationalCapabilities();
    }

    /**
     * Create an instance of {@link TPreconditionerRelationships }
     * 
     */
    public TPreconditionerRelationships createTPreconditionerRelationships() {
        return new TPreconditionerRelationships();
    }

    /**
     * Create an instance of {@link TRequiremens }
     * 
     */
    public TRequiremens createTRequiremens() {
        return new TRequiremens();
    }

    /**
     * Create an instance of {@link TAbstractIntention }
     * 
     */
    public TAbstractIntention createTAbstractIntention() {
        return new TAbstractIntention();
    }

    /**
     * Create an instance of {@link TStructuredProperties }
     * 
     */
    public TStructuredProperties createTStructuredProperties() {
        return new TStructuredProperties();
    }

    /**
     * Create an instance of {@link TDocumentation }
     * 
     */
    public TDocumentation createTDocumentation() {
        return new TDocumentation();
    }

    /**
     * Create an instance of {@link Definitions }
     * 
     */
    public Definitions createDefinitions() {
        return new Definitions();
    }

    /**
     * Create an instance of {@link TExtensibleElements }
     * 
     */
    public TExtensibleElements createTExtensibleElements() {
        return new TExtensibleElements();
    }

    /**
     * Create an instance of {@link TDefinitions.Extensions }
     * 
     */
    public TDefinitions.Extensions createTDefinitionsExtensions() {
        return new TDefinitions.Extensions();
    }

    /**
     * Create an instance of {@link TImport }
     * 
     */
    public TImport createTImport() {
        return new TImport();
    }

    /**
     * Create an instance of {@link TDefinitions.Types }
     * 
     */
    public TDefinitions.Types createTDefinitionsTypes() {
        return new TDefinitions.Types();
    }

    /**
     * Create an instance of {@link TServiceTemplate }
     * 
     */
    public TServiceTemplate createTServiceTemplate() {
        return new TServiceTemplate();
    }

    /**
     * Create an instance of {@link TRequirementType }
     * 
     */
    public TRequirementType createTRequirementType() {
        return new TRequirementType();
    }

    /**
     * Create an instance of {@link TCapabilityType }
     * 
     */
    public TCapabilityType createTCapabilityType() {
        return new TCapabilityType();
    }

    /**
     * Create an instance of {@link TArtifactType }
     * 
     */
    public TArtifactType createTArtifactType() {
        return new TArtifactType();
    }

    /**
     * Create an instance of {@link TPolicyType }
     * 
     */
    public TPolicyType createTPolicyType() {
        return new TPolicyType();
    }

    /**
     * Create an instance of {@link TPolicyTemplate }
     * 
     */
    public TPolicyTemplate createTPolicyTemplate() {
        return new TPolicyTemplate();
    }

    /**
     * Create an instance of {@link TRequirementRef }
     * 
     */
    public TRequirementRef createTRequirementRef() {
        return new TRequirementRef();
    }

    /**
     * Create an instance of {@link TImplementationArtifact }
     * 
     */
    public TImplementationArtifact createTImplementationArtifact() {
        return new TImplementationArtifact();
    }

    /**
     * Create an instance of {@link TParameter }
     * 
     */
    public TParameter createTParameter() {
        return new TParameter();
    }

    /**
     * Create an instance of {@link TExtension }
     * 
     */
    public TExtension createTExtension() {
        return new TExtension();
    }

    /**
     * Create an instance of {@link TDeploymentArtifact }
     * 
     */
    public TDeploymentArtifact createTDeploymentArtifact() {
        return new TDeploymentArtifact();
    }

    /**
     * Create an instance of {@link TRequiredContainerFeatures }
     * 
     */
    public TRequiredContainerFeatures createTRequiredContainerFeatures() {
        return new TRequiredContainerFeatures();
    }

    /**
     * Create an instance of {@link TExportedInterface }
     * 
     */
    public TExportedInterface createTExportedInterface() {
        return new TExportedInterface();
    }

    /**
     * Create an instance of {@link TConstraint }
     * 
     */
    public TConstraint createTConstraint() {
        return new TConstraint();
    }

    /**
     * Create an instance of {@link TPlans }
     * 
     */
    public TPlans createTPlans() {
        return new TPlans();
    }

    /**
     * Create an instance of {@link TPropertyMapping }
     * 
     */
    public TPropertyMapping createTPropertyMapping() {
        return new TPropertyMapping();
    }

    /**
     * Create an instance of {@link TCondition }
     * 
     */
    public TCondition createTCondition() {
        return new TCondition();
    }

    /**
     * Create an instance of {@link TExtensions }
     * 
     */
    public TExtensions createTExtensions() {
        return new TExtensions();
    }

    /**
     * Create an instance of {@link TTopologyTemplate }
     * 
     */
    public TTopologyTemplate createTTopologyTemplate() {
        return new TTopologyTemplate();
    }

    /**
     * Create an instance of {@link TTags }
     * 
     */
    public TTags createTTags() {
        return new TTags();
    }

    /**
     * Create an instance of {@link TPolicy }
     * 
     */
    public TPolicy createTPolicy() {
        return new TPolicy();
    }

    /**
     * Create an instance of {@link TRequiredContainerFeature }
     * 
     */
    public TRequiredContainerFeature createTRequiredContainerFeature() {
        return new TRequiredContainerFeature();
    }

    /**
     * Create an instance of {@link TDeploymentArtifacts }
     * 
     */
    public TDeploymentArtifacts createTDeploymentArtifacts() {
        return new TDeploymentArtifacts();
    }

    /**
     * Create an instance of {@link TCapability }
     * 
     */
    public TCapability createTCapability() {
        return new TCapability();
    }

    /**
     * Create an instance of {@link TPropertyConstraint }
     * 
     */
    public TPropertyConstraint createTPropertyConstraint() {
        return new TPropertyConstraint();
    }

    /**
     * Create an instance of {@link TTag }
     * 
     */
    public TTag createTTag() {
        return new TTag();
    }

    /**
     * Create an instance of {@link TInterface }
     * 
     */
    public TInterface createTInterface() {
        return new TInterface();
    }

    /**
     * Create an instance of {@link TRequirement }
     * 
     */
    public TRequirement createTRequirement() {
        return new TRequirement();
    }

    /**
     * Create an instance of {@link TCapabilityRef }
     * 
     */
    public TCapabilityRef createTCapabilityRef() {
        return new TCapabilityRef();
    }

    /**
     * Create an instance of {@link demo.TEntityTemplate.Properties }
     * 
     */
    public demo.TEntityTemplate.Properties createTEntityTemplateProperties() {
        return new demo.TEntityTemplate.Properties();
    }

    /**
     * Create an instance of {@link demo.TEntityTemplate.PropertyConstraints }
     * 
     */
    public demo.TEntityTemplate.PropertyConstraints createTEntityTemplatePropertyConstraints() {
        return new demo.TEntityTemplate.PropertyConstraints();
    }

    /**
     * Create an instance of {@link TRelationshipTemplate.SourceElement }
     * 
     */
    public TRelationshipTemplate.SourceElement createTRelationshipTemplateSourceElement() {
        return new TRelationshipTemplate.SourceElement();
    }

    /**
     * Create an instance of {@link TRelationshipTemplate.TargetElement }
     * 
     */
    public TRelationshipTemplate.TargetElement createTRelationshipTemplateTargetElement() {
        return new TRelationshipTemplate.TargetElement();
    }

    /**
     * Create an instance of {@link TRelationshipTemplate.RelationshipConstraints.RelationshipConstraint }
     * 
     */
    public TRelationshipTemplate.RelationshipConstraints.RelationshipConstraint createTRelationshipTemplateRelationshipConstraintsRelationshipConstraint() {
        return new TRelationshipTemplate.RelationshipConstraints.RelationshipConstraint();
    }

    /**
     * Create an instance of {@link TRequirementDefinition.Constraints }
     * 
     */
    public TRequirementDefinition.Constraints createTRequirementDefinitionConstraints() {
        return new TRequirementDefinition.Constraints();
    }

    /**
     * Create an instance of {@link TNodeTemplate.Requirements }
     * 
     */
    public TNodeTemplate.Requirements createTNodeTemplateRequirements() {
        return new TNodeTemplate.Requirements();
    }

    /**
     * Create an instance of {@link TNodeTemplate.Capabilities }
     * 
     */
    public TNodeTemplate.Capabilities createTNodeTemplateCapabilities() {
        return new TNodeTemplate.Capabilities();
    }

    /**
     * Create an instance of {@link TNodeTemplate.Policies }
     * 
     */
    public TNodeTemplate.Policies createTNodeTemplatePolicies() {
        return new TNodeTemplate.Policies();
    }

    /**
     * Create an instance of {@link TTopologyElementInstanceStates.InstanceState }
     * 
     */
    public TTopologyElementInstanceStates.InstanceState createTTopologyElementInstanceStatesInstanceState() {
        return new TTopologyElementInstanceStates.InstanceState();
    }

    /**
     * Create an instance of {@link TAppliesTo.NodeTypeReference }
     * 
     */
    public TAppliesTo.NodeTypeReference createTAppliesToNodeTypeReference() {
        return new TAppliesTo.NodeTypeReference();
    }

    /**
     * Create an instance of {@link TImplementationArtifacts.ImplementationArtifact }
     * 
     */
    public TImplementationArtifacts.ImplementationArtifact createTImplementationArtifactsImplementationArtifact() {
        return new TImplementationArtifacts.ImplementationArtifact();
    }

    /**
     * Create an instance of {@link TArtifactReference.Include }
     * 
     */
    public TArtifactReference.Include createTArtifactReferenceInclude() {
        return new TArtifactReference.Include();
    }

    /**
     * Create an instance of {@link TArtifactReference.Exclude }
     * 
     */
    public TArtifactReference.Exclude createTArtifactReferenceExclude() {
        return new TArtifactReference.Exclude();
    }

    /**
     * Create an instance of {@link demo.TEntityType.DerivedFrom }
     * 
     */
    public demo.TEntityType.DerivedFrom createTEntityTypeDerivedFrom() {
        return new demo.TEntityType.DerivedFrom();
    }

    /**
     * Create an instance of {@link demo.TEntityType.PropertiesDefinition }
     * 
     */
    public demo.TEntityType.PropertiesDefinition createTEntityTypePropertiesDefinition() {
        return new demo.TEntityType.PropertiesDefinition();
    }

    /**
     * Create an instance of {@link TBoundaryDefinitions.PropertyConstraints }
     * 
     */
    public TBoundaryDefinitions.PropertyConstraints createTBoundaryDefinitionsPropertyConstraints() {
        return new TBoundaryDefinitions.PropertyConstraints();
    }

    /**
     * Create an instance of {@link TBoundaryDefinitions.Requirements }
     * 
     */
    public TBoundaryDefinitions.Requirements createTBoundaryDefinitionsRequirements() {
        return new TBoundaryDefinitions.Requirements();
    }

    /**
     * Create an instance of {@link TBoundaryDefinitions.Capabilities }
     * 
     */
    public TBoundaryDefinitions.Capabilities createTBoundaryDefinitionsCapabilities() {
        return new TBoundaryDefinitions.Capabilities();
    }

    /**
     * Create an instance of {@link TBoundaryDefinitions.Policies }
     * 
     */
    public TBoundaryDefinitions.Policies createTBoundaryDefinitionsPolicies() {
        return new TBoundaryDefinitions.Policies();
    }

    /**
     * Create an instance of {@link TBoundaryDefinitions.Interfaces }
     * 
     */
    public TBoundaryDefinitions.Interfaces createTBoundaryDefinitionsInterfaces() {
        return new TBoundaryDefinitions.Interfaces();
    }

    /**
     * Create an instance of {@link TBoundaryDefinitions.Properties.PropertyMappings }
     * 
     */
    public TBoundaryDefinitions.Properties.PropertyMappings createTBoundaryDefinitionsPropertiesPropertyMappings() {
        return new TBoundaryDefinitions.Properties.PropertyMappings();
    }

    /**
     * Create an instance of {@link TExportedOperation.NodeOperation }
     * 
     */
    public TExportedOperation.NodeOperation createTExportedOperationNodeOperation() {
        return new TExportedOperation.NodeOperation();
    }

    /**
     * Create an instance of {@link TExportedOperation.RelationshipOperation }
     * 
     */
    public TExportedOperation.RelationshipOperation createTExportedOperationRelationshipOperation() {
        return new TExportedOperation.RelationshipOperation();
    }

    /**
     * Create an instance of {@link TExportedOperation.Plan }
     * 
     */
    public TExportedOperation.Plan createTExportedOperationPlan() {
        return new TExportedOperation.Plan();
    }

    /**
     * Create an instance of {@link TPlan.InputParameters }
     * 
     */
    public TPlan.InputParameters createTPlanInputParameters() {
        return new TPlan.InputParameters();
    }

    /**
     * Create an instance of {@link TPlan.OutputParameters }
     * 
     */
    public TPlan.OutputParameters createTPlanOutputParameters() {
        return new TPlan.OutputParameters();
    }

    /**
     * Create an instance of {@link TPlan.PlanModel }
     * 
     */
    public TPlan.PlanModel createTPlanPlanModel() {
        return new TPlan.PlanModel();
    }

    /**
     * Create an instance of {@link TPlan.PlanModelReference }
     * 
     */
    public TPlan.PlanModelReference createTPlanPlanModelReference() {
        return new TPlan.PlanModelReference();
    }

    /**
     * Create an instance of {@link TCapabilityDefinition.Constraints }
     * 
     */
    public TCapabilityDefinition.Constraints createTCapabilityDefinitionConstraints() {
        return new TCapabilityDefinition.Constraints();
    }

    /**
     * Create an instance of {@link TOperation.InputParameters }
     * 
     */
    public TOperation.InputParameters createTOperationInputParameters() {
        return new TOperation.InputParameters();
    }

    /**
     * Create an instance of {@link TOperation.OutputParameters }
     * 
     */
    public TOperation.OutputParameters createTOperationOutputParameters() {
        return new TOperation.OutputParameters();
    }

    /**
     * Create an instance of {@link TArtifactTemplate.ArtifactReferences }
     * 
     */
    public TArtifactTemplate.ArtifactReferences createTArtifactTemplateArtifactReferences() {
        return new TArtifactTemplate.ArtifactReferences();
    }

    /**
     * Create an instance of {@link TRelationshipTypeImplementation.DerivedFrom }
     * 
     */
    public TRelationshipTypeImplementation.DerivedFrom createTRelationshipTypeImplementationDerivedFrom() {
        return new TRelationshipTypeImplementation.DerivedFrom();
    }

    /**
     * Create an instance of {@link TRelationshipType.SourceInterfaces }
     * 
     */
    public TRelationshipType.SourceInterfaces createTRelationshipTypeSourceInterfaces() {
        return new TRelationshipType.SourceInterfaces();
    }

    /**
     * Create an instance of {@link TRelationshipType.TargetInterfaces }
     * 
     */
    public TRelationshipType.TargetInterfaces createTRelationshipTypeTargetInterfaces() {
        return new TRelationshipType.TargetInterfaces();
    }

    /**
     * Create an instance of {@link TRelationshipType.ValidSource }
     * 
     */
    public TRelationshipType.ValidSource createTRelationshipTypeValidSource() {
        return new TRelationshipType.ValidSource();
    }

    /**
     * Create an instance of {@link TRelationshipType.ValidTarget }
     * 
     */
    public TRelationshipType.ValidTarget createTRelationshipTypeValidTarget() {
        return new TRelationshipType.ValidTarget();
    }

    /**
     * Create an instance of {@link TNodeTypeImplementation.DerivedFrom }
     * 
     */
    public TNodeTypeImplementation.DerivedFrom createTNodeTypeImplementationDerivedFrom() {
        return new TNodeTypeImplementation.DerivedFrom();
    }

    /**
     * Create an instance of {@link TNodeType.RequirementDefinitions }
     * 
     */
    public TNodeType.RequirementDefinitions createTNodeTypeRequirementDefinitions() {
        return new TNodeType.RequirementDefinitions();
    }

    /**
     * Create an instance of {@link TNodeType.CapabilityDefinitions }
     * 
     */
    public TNodeType.CapabilityDefinitions createTNodeTypeCapabilityDefinitions() {
        return new TNodeType.CapabilityDefinitions();
    }

    /**
     * Create an instance of {@link TNodeType.Interfaces }
     * 
     */
    public TNodeType.Interfaces createTNodeTypeInterfaces() {
        return new TNodeType.Interfaces();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TDocumentation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/tosca/ns/2011/12", name = "documentation")
    public JAXBElement<TDocumentation> createDocumentation(TDocumentation value) {
        return new JAXBElement<TDocumentation>(_Documentation_QNAME, TDocumentation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TInformalProcessInstance }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.uni-stuttgart.de/iaas/ipsm/v0.2/", name = "InformalProcessInstance")
    public JAXBElement<TInformalProcessInstance> createInformalProcessInstance(TInformalProcessInstance value) {
        return new JAXBElement<TInformalProcessInstance>(_InformalProcessInstance_QNAME, TInformalProcessInstance.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TOrganizationalDefinitions }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.uni-stuttgart.de/iaas/ipsm/v0.2/", name = "OrganizationalDefinitions")
    public JAXBElement<TOrganizationalDefinitions> createOrganizationalDefinitions(TOrganizationalDefinitions value) {
        return new JAXBElement<TOrganizationalDefinitions>(_OrganizationalDefinitions_QNAME, TOrganizationalDefinitions.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TInformalProcessDefinition }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.uni-stuttgart.de/iaas/ipsm/v0.2/", name = "InformalProcessDefinition")
    public JAXBElement<TInformalProcessDefinition> createInformalProcessDefinition(TInformalProcessDefinition value) {
        return new JAXBElement<TInformalProcessDefinition>(_InformalProcessDefinition_QNAME, TInformalProcessDefinition.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TOperationMessage }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.uni-stuttgart.de/iaas/ipsm/v0.2/", name = "OperationMessage")
    public JAXBElement<TOperationMessage> createOperationMessage(TOperationMessage value) {
        return new JAXBElement<TOperationMessage>(_OperationMessage_QNAME, TOperationMessage.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TProcessDefinition }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.uni-stuttgart.de/iaas/ipsm/v0.2/", name = "ProcessDefinition")
    public JAXBElement<TProcessDefinition> createProcessDefinition(TProcessDefinition value) {
        return new JAXBElement<TProcessDefinition>(_ProcessDefinition_QNAME, TProcessDefinition.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TProcessInstance }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.uni-stuttgart.de/iaas/ipsm/v0.2/", name = "ProcessInstance")
    public JAXBElement<TProcessInstance> createProcessInstance(TProcessInstance value) {
        return new JAXBElement<TProcessInstance>(_ProcessInstance_QNAME, TProcessInstance.class, null, value);
    }

}
