//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.15 at 03:46:13 AM CET 
//


package demo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tAbstractIntention complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tAbstractIntention">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.uni-stuttgart.de/iaas/ipsm/v0.2/}tIntention">
 *       &lt;sequence>
 *         &lt;element name="Strategies" type="{http://www.uni-stuttgart.de/iaas/ipsm/v0.2/}tStrategy" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tAbstractIntention", namespace = "http://www.uni-stuttgart.de/iaas/ipsm/v0.2/", propOrder = {
    "strategies"
})
public class TAbstractIntention
    extends TIntention
{

    @XmlElement(name = "Strategies")
    protected List<TStrategy> strategies;

    /**
     * Gets the value of the strategies property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the strategies property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStrategies().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TStrategy }
     * 
     * 
     */
    public List<TStrategy> getStrategies() {
        if (strategies == null) {
            strategies = new ArrayList<TStrategy>();
        }
        return this.strategies;
    }

}
