//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.15 at 03:46:13 AM CET 
//


package demo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tConcreteIntention complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tConcreteIntention">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.uni-stuttgart.de/iaas/ipsm/v0.2/}tIntention">
 *       &lt;sequence>
 *         &lt;element name="OrganizationalCapabilities" type="{http://www.uni-stuttgart.de/iaas/ipsm/v0.2/}tOrganizationalCapabilities"/>
 *         &lt;element name="SubIntentions" type="{http://www.uni-stuttgart.de/iaas/ipsm/v0.2/}tIntentions" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tConcreteIntention", namespace = "http://www.uni-stuttgart.de/iaas/ipsm/v0.2/", propOrder = {
    "organizationalCapabilities",
    "subIntentions"
})
public class TConcreteIntention
    extends TIntention
{

    @XmlElement(name = "OrganizationalCapabilities", required = true)
    protected TOrganizationalCapabilities organizationalCapabilities;
    @XmlElement(name = "SubIntentions")
    protected TIntentions subIntentions;

    /**
     * Gets the value of the organizationalCapabilities property.
     * 
     * @return
     *     possible object is
     *     {@link TOrganizationalCapabilities }
     *     
     */
    public TOrganizationalCapabilities getOrganizationalCapabilities() {
        return organizationalCapabilities;
    }

    /**
     * Sets the value of the organizationalCapabilities property.
     * 
     * @param value
     *     allowed object is
     *     {@link TOrganizationalCapabilities }
     *     
     */
    public void setOrganizationalCapabilities(TOrganizationalCapabilities value) {
        this.organizationalCapabilities = value;
    }

    /**
     * Gets the value of the subIntentions property.
     * 
     * @return
     *     possible object is
     *     {@link TIntentions }
     *     
     */
    public TIntentions getSubIntentions() {
        return subIntentions;
    }

    /**
     * Sets the value of the subIntentions property.
     * 
     * @param value
     *     allowed object is
     *     {@link TIntentions }
     *     
     */
    public void setSubIntentions(TIntentions value) {
        this.subIntentions = value;
    }

}
