//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.15 at 03:46:13 AM CET 
//


package demo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tDefinition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tDefinition">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DefinitionContent" type="{http://www.uni-stuttgart.de/iaas/ipsm/v0.2/}tContent"/>
 *       &lt;/sequence>
 *       &lt;attribute name="definitionLanguage" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tDefinition", namespace = "http://www.uni-stuttgart.de/iaas/ipsm/v0.2/", propOrder = {
    "definitionContent"
})
public class TDefinition {

    @XmlElement(name = "DefinitionContent", required = true)
    protected TContent definitionContent;
    @XmlAttribute(name = "definitionLanguage")
    @XmlSchemaType(name = "anyURI")
    protected String definitionLanguage;

    /**
     * Gets the value of the definitionContent property.
     * 
     * @return
     *     possible object is
     *     {@link TContent }
     *     
     */
    public TContent getDefinitionContent() {
        return definitionContent;
    }

    /**
     * Sets the value of the definitionContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link TContent }
     *     
     */
    public void setDefinitionContent(TContent value) {
        this.definitionContent = value;
    }

    /**
     * Gets the value of the definitionLanguage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefinitionLanguage() {
        return definitionLanguage;
    }

    /**
     * Sets the value of the definitionLanguage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefinitionLanguage(String value) {
        this.definitionLanguage = value;
    }

}
