//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.15 at 03:46:13 AM CET 
//


package demo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tDeploymentDescriptor complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tDeploymentDescriptor">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="runnableUri" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="executionEnvironment" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="runnableName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tDeploymentDescriptor", namespace = "http://www.uni-stuttgart.de/iaas/ipsm/v0.2/")
public class TDeploymentDescriptor {

    @XmlAttribute(name = "runnableUri")
    @XmlSchemaType(name = "anyURI")
    protected String runnableUri;
    @XmlAttribute(name = "executionEnvironment")
    @XmlSchemaType(name = "anyURI")
    protected String executionEnvironment;
    @XmlAttribute(name = "runnableName")
    protected String runnableName;

    /**
     * Gets the value of the runnableUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRunnableUri() {
        return runnableUri;
    }

    /**
     * Sets the value of the runnableUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRunnableUri(String value) {
        this.runnableUri = value;
    }

    /**
     * Gets the value of the executionEnvironment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExecutionEnvironment() {
        return executionEnvironment;
    }

    /**
     * Sets the value of the executionEnvironment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExecutionEnvironment(String value) {
        this.executionEnvironment = value;
    }

    /**
     * Gets the value of the runnableName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRunnableName() {
        return runnableName;
    }

    /**
     * Sets the value of the runnableName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRunnableName(String value) {
        this.runnableName = value;
    }

}
