//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.15 at 03:46:13 AM CET 
//


package demo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tInformalProcessInstance complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tInformalProcessInstance">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.uni-stuttgart.de/iaas/ipsm/v0.2/}tProcessInstance">
 *       &lt;sequence>
 *         &lt;element name="ResourceModelInstance" type="{http://www.uni-stuttgart.de/iaas/ipsm/v0.2/}tResourceModelInstance"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tInformalProcessInstance", namespace = "http://www.uni-stuttgart.de/iaas/ipsm/v0.2/", propOrder = {
    "resourceModelInstance"
})
public class TInformalProcessInstance
    extends TProcessInstance
{

    @XmlElement(name = "ResourceModelInstance", required = true)
    protected TResourceModelInstance resourceModelInstance;

    /**
     * Gets the value of the resourceModelInstance property.
     * 
     * @return
     *     possible object is
     *     {@link TResourceModelInstance }
     *     
     */
    public TResourceModelInstance getResourceModelInstance() {
        return resourceModelInstance;
    }

    /**
     * Sets the value of the resourceModelInstance property.
     * 
     * @param value
     *     allowed object is
     *     {@link TResourceModelInstance }
     *     
     */
    public void setResourceModelInstance(TResourceModelInstance value) {
        this.resourceModelInstance = value;
    }

}
