//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.15 at 03:46:13 AM CET 
//


package demo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tOperationMessage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tOperationMessage">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PreconditionerRelationships" type="{http://www.uni-stuttgart.de/iaas/ipsm/v0.2/}tPreconditionerRelationships" minOccurs="0"/>
 *         &lt;element name="Dependencies" type="{http://www.uni-stuttgart.de/iaas/ipsm/v0.2/}tDependencies" minOccurs="0"/>
 *         &lt;element name="InstanceLocation" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="ErrorDefinition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="InstanceState" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TargetResource" type="{http://docs.oasis-open.org/tosca/ns/2011/12}tNodeTemplate"/>
 *         &lt;element name="InformalProcessInstance" type="{http://www.uni-stuttgart.de/iaas/ipsm/v0.2/}tInformalProcessInstance" minOccurs="0"/>
 *         &lt;element name="OtherParameters" type="{http://www.uni-stuttgart.de/iaas/ipsm/v0.2/}tOtherParameters" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="processId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="operationType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tOperationMessage", namespace = "http://www.uni-stuttgart.de/iaas/ipsm/v0.2/", propOrder = {
    "preconditionerRelationships",
    "dependencies",
    "instanceLocation",
    "errorDefinition",
    "instanceState",
    "targetResource",
    "informalProcessInstance",
    "otherParameters"
})
public class TOperationMessage {

    @XmlElement(name = "PreconditionerRelationships")
    protected TPreconditionerRelationships preconditionerRelationships;
    @XmlElement(name = "Dependencies")
    protected TDependencies dependencies;
    @XmlElement(name = "InstanceLocation")
    @XmlSchemaType(name = "anyURI")
    protected String instanceLocation;
    @XmlElement(name = "ErrorDefinition")
    protected String errorDefinition;
    @XmlElement(name = "InstanceState")
    protected String instanceState;
    @XmlElement(name = "TargetResource", required = true)
    protected TNodeTemplate targetResource;
    @XmlElement(name = "InformalProcessInstance")
    protected TInformalProcessInstance informalProcessInstance;
    @XmlElement(name = "OtherParameters")
    protected TOtherParameters otherParameters;
    @XmlAttribute(name = "processId")
    protected String processId;
    @XmlAttribute(name = "operationType")
    protected String operationType;

    /**
     * Gets the value of the preconditionerRelationships property.
     * 
     * @return
     *     possible object is
     *     {@link TPreconditionerRelationships }
     *     
     */
    public TPreconditionerRelationships getPreconditionerRelationships() {
        return preconditionerRelationships;
    }

    /**
     * Sets the value of the preconditionerRelationships property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPreconditionerRelationships }
     *     
     */
    public void setPreconditionerRelationships(TPreconditionerRelationships value) {
        this.preconditionerRelationships = value;
    }

    /**
     * Gets the value of the dependencies property.
     * 
     * @return
     *     possible object is
     *     {@link TDependencies }
     *     
     */
    public TDependencies getDependencies() {
        return dependencies;
    }

    /**
     * Sets the value of the dependencies property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDependencies }
     *     
     */
    public void setDependencies(TDependencies value) {
        this.dependencies = value;
    }

    /**
     * Gets the value of the instanceLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstanceLocation() {
        return instanceLocation;
    }

    /**
     * Sets the value of the instanceLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstanceLocation(String value) {
        this.instanceLocation = value;
    }

    /**
     * Gets the value of the errorDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorDefinition() {
        return errorDefinition;
    }

    /**
     * Sets the value of the errorDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorDefinition(String value) {
        this.errorDefinition = value;
    }

    /**
     * Gets the value of the instanceState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstanceState() {
        return instanceState;
    }

    /**
     * Sets the value of the instanceState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstanceState(String value) {
        this.instanceState = value;
    }

    /**
     * Gets the value of the targetResource property.
     * 
     * @return
     *     possible object is
     *     {@link TNodeTemplate }
     *     
     */
    public TNodeTemplate getTargetResource() {
        return targetResource;
    }

    /**
     * Sets the value of the targetResource property.
     * 
     * @param value
     *     allowed object is
     *     {@link TNodeTemplate }
     *     
     */
    public void setTargetResource(TNodeTemplate value) {
        this.targetResource = value;
    }

    /**
     * Gets the value of the informalProcessInstance property.
     * 
     * @return
     *     possible object is
     *     {@link TInformalProcessInstance }
     *     
     */
    public TInformalProcessInstance getInformalProcessInstance() {
        return informalProcessInstance;
    }

    /**
     * Sets the value of the informalProcessInstance property.
     * 
     * @param value
     *     allowed object is
     *     {@link TInformalProcessInstance }
     *     
     */
    public void setInformalProcessInstance(TInformalProcessInstance value) {
        this.informalProcessInstance = value;
    }

    /**
     * Gets the value of the otherParameters property.
     * 
     * @return
     *     possible object is
     *     {@link TOtherParameters }
     *     
     */
    public TOtherParameters getOtherParameters() {
        return otherParameters;
    }

    /**
     * Sets the value of the otherParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link TOtherParameters }
     *     
     */
    public void setOtherParameters(TOtherParameters value) {
        this.otherParameters = value;
    }

    /**
     * Gets the value of the processId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessId() {
        return processId;
    }

    /**
     * Sets the value of the processId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessId(String value) {
        this.processId = value;
    }

    /**
     * Gets the value of the operationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperationType() {
        return operationType;
    }

    /**
     * Sets the value of the operationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperationType(String value) {
        this.operationType = value;
    }

}
