//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.15 at 03:46:13 AM CET 
//


package demo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tOrganizationalDefinitions complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tOrganizationalDefinitions">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.uni-stuttgart.de/iaas/ipsm/v0.2/}tBaseType">
 *       &lt;sequence>
 *         &lt;element name="OrganizationalIntentions" type="{http://www.uni-stuttgart.de/iaas/ipsm/v0.2/}tAbstractIntentions" minOccurs="0"/>
 *         &lt;element name="OrganizationallResources" type="{http://docs.oasis-open.org/tosca/ns/2011/12}tDefinitions" minOccurs="0"/>
 *         &lt;element name="OrganizationalProcesses" type="{http://www.uni-stuttgart.de/iaas/ipsm/v0.2/}tOrganizationalProcesses" minOccurs="0"/>
 *         &lt;element name="OrganizationalProcessInstances" type="{http://www.uni-stuttgart.de/iaas/ipsm/v0.2/}tProcessInstances" minOccurs="0"/>
 *         &lt;element name="OrganizationalCapabilities" type="{http://www.uni-stuttgart.de/iaas/ipsm/v0.2/}tOrganizationalCapabilities" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tOrganizationalDefinitions", namespace = "http://www.uni-stuttgart.de/iaas/ipsm/v0.2/", propOrder = {
    "organizationalIntentions",
    "organizationallResources",
    "organizationalProcesses",
    "organizationalProcessInstances",
    "organizationalCapabilities"
})
public class TOrganizationalDefinitions
    extends TBaseType
{

    @XmlElement(name = "OrganizationalIntentions")
    protected TAbstractIntentions organizationalIntentions;
    @XmlElement(name = "OrganizationallResources")
    protected TDefinitions organizationallResources;
    @XmlElement(name = "OrganizationalProcesses")
    protected TOrganizationalProcesses organizationalProcesses;
    @XmlElement(name = "OrganizationalProcessInstances")
    protected TProcessInstances organizationalProcessInstances;
    @XmlElement(name = "OrganizationalCapabilities")
    protected TOrganizationalCapabilities organizationalCapabilities;

    /**
     * Gets the value of the organizationalIntentions property.
     * 
     * @return
     *     possible object is
     *     {@link TAbstractIntentions }
     *     
     */
    public TAbstractIntentions getOrganizationalIntentions() {
        return organizationalIntentions;
    }

    /**
     * Sets the value of the organizationalIntentions property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAbstractIntentions }
     *     
     */
    public void setOrganizationalIntentions(TAbstractIntentions value) {
        this.organizationalIntentions = value;
    }

    /**
     * Gets the value of the organizationallResources property.
     * 
     * @return
     *     possible object is
     *     {@link TDefinitions }
     *     
     */
    public TDefinitions getOrganizationallResources() {
        return organizationallResources;
    }

    /**
     * Sets the value of the organizationallResources property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDefinitions }
     *     
     */
    public void setOrganizationallResources(TDefinitions value) {
        this.organizationallResources = value;
    }

    /**
     * Gets the value of the organizationalProcesses property.
     * 
     * @return
     *     possible object is
     *     {@link TOrganizationalProcesses }
     *     
     */
    public TOrganizationalProcesses getOrganizationalProcesses() {
        return organizationalProcesses;
    }

    /**
     * Sets the value of the organizationalProcesses property.
     * 
     * @param value
     *     allowed object is
     *     {@link TOrganizationalProcesses }
     *     
     */
    public void setOrganizationalProcesses(TOrganizationalProcesses value) {
        this.organizationalProcesses = value;
    }

    /**
     * Gets the value of the organizationalProcessInstances property.
     * 
     * @return
     *     possible object is
     *     {@link TProcessInstances }
     *     
     */
    public TProcessInstances getOrganizationalProcessInstances() {
        return organizationalProcessInstances;
    }

    /**
     * Sets the value of the organizationalProcessInstances property.
     * 
     * @param value
     *     allowed object is
     *     {@link TProcessInstances }
     *     
     */
    public void setOrganizationalProcessInstances(TProcessInstances value) {
        this.organizationalProcessInstances = value;
    }

    /**
     * Gets the value of the organizationalCapabilities property.
     * 
     * @return
     *     possible object is
     *     {@link TOrganizationalCapabilities }
     *     
     */
    public TOrganizationalCapabilities getOrganizationalCapabilities() {
        return organizationalCapabilities;
    }

    /**
     * Sets the value of the organizationalCapabilities property.
     * 
     * @param value
     *     allowed object is
     *     {@link TOrganizationalCapabilities }
     *     
     */
    public void setOrganizationalCapabilities(TOrganizationalCapabilities value) {
        this.organizationalCapabilities = value;
    }

}
