//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.15 at 03:46:13 AM CET 
//


package demo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tOrganizationalCapability complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tOrganizationalCapability">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ProvidingResources" type="{http://www.uni-stuttgart.de/iaas/ipsm/v0.2/}tProvidingResources" minOccurs="0"/>
 *         &lt;element name="CapabilityType" type="{http://docs.oasis-open.org/tosca/ns/2011/12}tCapabilityType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tOrganizationalCapability", namespace = "http://www.uni-stuttgart.de/iaas/ipsm/v0.2/", propOrder = {
    "providingResources",
    "capabilityType"
})
public class TOrganizationalCapability {

    @XmlElement(name = "ProvidingResources")
    protected TProvidingResources providingResources;
    @XmlElement(name = "CapabilityType", required = true)
    protected TCapabilityType capabilityType;

    /**
     * Gets the value of the providingResources property.
     * 
     * @return
     *     possible object is
     *     {@link TProvidingResources }
     *     
     */
    public TProvidingResources getProvidingResources() {
        return providingResources;
    }

    /**
     * Sets the value of the providingResources property.
     * 
     * @param value
     *     allowed object is
     *     {@link TProvidingResources }
     *     
     */
    public void setProvidingResources(TProvidingResources value) {
        this.providingResources = value;
    }

    /**
     * Gets the value of the capabilityType property.
     * 
     * @return
     *     possible object is
     *     {@link TCapabilityType }
     *     
     */
    public TCapabilityType getCapabilityType() {
        return capabilityType;
    }

    /**
     * Sets the value of the capabilityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TCapabilityType }
     *     
     */
    public void setCapabilityType(TCapabilityType value) {
        this.capabilityType = value;
    }

}
