//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.15 at 03:46:13 AM CET 
//


package demo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tProperties complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tProperties">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Tags" type="{http://docs.oasis-open.org/tosca/ns/2011/12}tTags"/>
 *         &lt;element name="StructuredProperties" type="{http://www.uni-stuttgart.de/iaas/ipsm/v0.2/}tStructuredProperties"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tProperties", namespace = "http://www.uni-stuttgart.de/iaas/ipsm/v0.2/", propOrder = {
    "tags",
    "structuredProperties"
})
public class TProperties {

    @XmlElement(name = "Tags", required = true)
    protected TTags tags;
    @XmlElement(name = "StructuredProperties", required = true)
    protected TStructuredProperties structuredProperties;

    /**
     * Gets the value of the tags property.
     * 
     * @return
     *     possible object is
     *     {@link TTags }
     *     
     */
    public TTags getTags() {
        return tags;
    }

    /**
     * Sets the value of the tags property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTags }
     *     
     */
    public void setTags(TTags value) {
        this.tags = value;
    }

    /**
     * Gets the value of the structuredProperties property.
     * 
     * @return
     *     possible object is
     *     {@link TStructuredProperties }
     *     
     */
    public TStructuredProperties getStructuredProperties() {
        return structuredProperties;
    }

    /**
     * Sets the value of the structuredProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link TStructuredProperties }
     *     
     */
    public void setStructuredProperties(TStructuredProperties value) {
        this.structuredProperties = value;
    }

}
