//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.15 at 03:46:13 AM CET 
//


package demo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tProcessInstance complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tProcessInstance">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.uni-stuttgart.de/iaas/ipsm/v0.2/}tProcessDefinition">
 *       &lt;sequence>
 *         &lt;element name="InstanceDescriptor" type="{http://www.uni-stuttgart.de/iaas/ipsm/v0.2/}tInstanceDescriptor"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tProcessInstance", namespace = "http://www.uni-stuttgart.de/iaas/ipsm/v0.2/", propOrder = {
    "instanceDescriptor"
})
@XmlSeeAlso({
    TInformalProcessInstance.class
})
public class TProcessInstance
    extends TProcessDefinition
{

    @XmlElement(name = "InstanceDescriptor", required = true)
    protected TInstanceDescriptor instanceDescriptor;

    /**
     * Gets the value of the instanceDescriptor property.
     * 
     * @return
     *     possible object is
     *     {@link TInstanceDescriptor }
     *     
     */
    public TInstanceDescriptor getInstanceDescriptor() {
        return instanceDescriptor;
    }

    /**
     * Sets the value of the instanceDescriptor property.
     * 
     * @param value
     *     allowed object is
     *     {@link TInstanceDescriptor }
     *     
     */
    public void setInstanceDescriptor(TInstanceDescriptor value) {
        this.instanceDescriptor = value;
    }

}
