//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.15 at 03:46:13 AM CET 
//


package demo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tResourceReferences complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tResourceReferences">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ResourceDefinition" type="{http://docs.oasis-open.org/tosca/ns/2011/12}tNodeTemplate"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tResourceReferences", namespace = "http://www.uni-stuttgart.de/iaas/ipsm/v0.2/", propOrder = {
    "resourceDefinition"
})
public class TResourceReferences {

    @XmlElement(name = "ResourceDefinition", required = true)
    protected TNodeTemplate resourceDefinition;

    /**
     * Gets the value of the resourceDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link TNodeTemplate }
     *     
     */
    public TNodeTemplate getResourceDefinition() {
        return resourceDefinition;
    }

    /**
     * Sets the value of the resourceDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link TNodeTemplate }
     *     
     */
    public void setResourceDefinition(TNodeTemplate value) {
        this.resourceDefinition = value;
    }

}
