//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.15 at 04:11:36 AM CET 
//


package unistuttgart.iaas.spi.cmprocess.cmp;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the unistuttgart.iaas.spi.cmprocess.cmp package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: unistuttgart.iaas.spi.cmprocess.cmp
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TProcessDefinition }
     * 
     */
    public TProcessDefinition createTProcessDefinition() {
        return new TProcessDefinition();
    }

    /**
     * Create an instance of {@link TProcessSet }
     * 
     */
    public TProcessSet createTProcessSet() {
        return new TProcessSet();
    }

    /**
     * Create an instance of {@link TData }
     * 
     */
    public TData createTData() {
        return new TData();
    }

    /**
     * Create an instance of {@link TContexts }
     * 
     */
    public TContexts createTContexts() {
        return new TContexts();
    }

    /**
     * Create an instance of {@link TCESTask }
     * 
     */
    public TCESTask createTCESTask() {
        return new TCESTask();
    }

    /**
     * Create an instance of {@link TLocationType }
     * 
     */
    public TLocationType createTLocationType() {
        return new TLocationType();
    }

    /**
     * Create an instance of {@link TIntention }
     * 
     */
    public TIntention createTIntention() {
        return new TIntention();
    }

    /**
     * Create an instance of {@link TDataList }
     * 
     */
    public TDataList createTDataList() {
        return new TDataList();
    }

    /**
     * Create an instance of {@link TDefinition }
     * 
     */
    public TDefinition createTDefinition() {
        return new TDefinition();
    }

    /**
     * Create an instance of {@link TContent }
     * 
     */
    public TContent createTContent() {
        return new TContent();
    }

    /**
     * Create an instance of {@link TContext }
     * 
     */
    public TContext createTContext() {
        return new TContext();
    }

    /**
     * Create an instance of {@link TContextExpressions }
     * 
     */
    public TContextExpressions createTContextExpressions() {
        return new TContextExpressions();
    }

    /**
     * Create an instance of {@link TIntentions }
     * 
     */
    public TIntentions createTIntentions() {
        return new TIntentions();
    }

    /**
     * Create an instance of {@link TContextExpression }
     * 
     */
    public TContextExpression createTContextExpression() {
        return new TContextExpression();
    }

}
