//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.16 at 01:31:56 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.uni-stuttgart.de/iaas/cmp/v0.1/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package unistuttgart.iaas.spi.cmprocess.cmp;
