//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.15 at 04:11:36 AM CET 
//


package unistuttgart.iaas.spi.cmprocess.cmp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tCESTask complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tCESTask">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.uni-stuttgart.de/iaas/cmp/v0.1/}tBaseType">
 *       &lt;sequence>
 *         &lt;element name="Intention" type="{http://www.uni-stuttgart.de/iaas/cmp/v0.1/}tIntention"/>
 *         &lt;element name="RequiredContext" type="{http://www.uni-stuttgart.de/iaas/cmp/v0.1/}tContexts"/>
 *         &lt;element name="InputData" type="{http://www.uni-stuttgart.de/iaas/cmp/v0.1/}tDataList" minOccurs="0"/>
 *         &lt;element name="OutputData" type="{http://www.uni-stuttgart.de/iaas/cmp/v0.1/}tDataList" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="isEventDriven" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="isCommandAction" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tCESTask", propOrder = {
    "intention",
    "requiredContext",
    "inputData",
    "outputData"
})
@XmlRootElement
public class TCESTask
    extends TBaseType
{

    @XmlElement(name = "Intention", required = true)
    protected TIntention intention;
    @XmlElement(name = "RequiredContext", required = true)
    protected TContexts requiredContext;
    @XmlElement(name = "InputData")
    protected TDataList inputData;
    @XmlElement(name = "OutputData")
    protected TDataList outputData;
    @XmlAttribute(name = "isEventDriven")
    protected Boolean isEventDriven;
    @XmlAttribute(name = "isCommandAction")
    protected Boolean isCommandAction;

    /**
     * Gets the value of the intention property.
     * 
     * @return
     *     possible object is
     *     {@link TIntention }
     *     
     */
    public TIntention getIntention() {
        return intention;
    }

    /**
     * Sets the value of the intention property.
     * 
     * @param value
     *     allowed object is
     *     {@link TIntention }
     *     
     */
    public void setIntention(TIntention value) {
        this.intention = value;
    }

    /**
     * Gets the value of the requiredContext property.
     * 
     * @return
     *     possible object is
     *     {@link TContexts }
     *     
     */
    public TContexts getRequiredContext() {
        return requiredContext;
    }

    /**
     * Sets the value of the requiredContext property.
     * 
     * @param value
     *     allowed object is
     *     {@link TContexts }
     *     
     */
    public void setRequiredContext(TContexts value) {
        this.requiredContext = value;
    }

    /**
     * Gets the value of the inputData property.
     * 
     * @return
     *     possible object is
     *     {@link TDataList }
     *     
     */
    public TDataList getInputData() {
        return inputData;
    }

    /**
     * Sets the value of the inputData property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDataList }
     *     
     */
    public void setInputData(TDataList value) {
        this.inputData = value;
    }

    /**
     * Gets the value of the outputData property.
     * 
     * @return
     *     possible object is
     *     {@link TDataList }
     *     
     */
    public TDataList getOutputData() {
        return outputData;
    }

    /**
     * Sets the value of the outputData property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDataList }
     *     
     */
    public void setOutputData(TDataList value) {
        this.outputData = value;
    }

    /**
     * Gets the value of the isEventDriven property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsEventDriven() {
        return isEventDriven;
    }

    /**
     * Sets the value of the isEventDriven property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsEventDriven(Boolean value) {
        this.isEventDriven = value;
    }

    /**
     * Gets the value of the isCommandAction property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsCommandAction() {
        return isCommandAction;
    }

    /**
     * Sets the value of the isCommandAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsCommandAction(Boolean value) {
        this.isCommandAction = value;
    }

}
