//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.15 at 04:11:36 AM CET 
//


package unistuttgart.iaas.spi.cmprocess.cmp;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tContext complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tContext">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.uni-stuttgart.de/iaas/cmp/v0.1/}tBaseType">
 *       &lt;sequence>
 *         &lt;element name="ContextDefinition" type="{http://www.uni-stuttgart.de/iaas/cmp/v0.1/}tDefinition" maxOccurs="unbounded"/>
 *         &lt;element name="ContainedContexts" type="{http://www.uni-stuttgart.de/iaas/cmp/v0.1/}tContexts" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tContext", propOrder = {
    "contextDefinition",
    "containedContexts"
})
public class TContext
    extends TBaseType
{

    @XmlElement(name = "ContextDefinition", required = true)
    protected List<TDefinition> contextDefinition;
    @XmlElement(name = "ContainedContexts")
    protected TContexts containedContexts;

    /**
     * Gets the value of the contextDefinition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contextDefinition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContextDefinition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TDefinition }
     * 
     * 
     */
    public List<TDefinition> getContextDefinition() {
        if (contextDefinition == null) {
            contextDefinition = new ArrayList<TDefinition>();
        }
        return this.contextDefinition;
    }

    /**
     * Gets the value of the containedContexts property.
     * 
     * @return
     *     possible object is
     *     {@link TContexts }
     *     
     */
    public TContexts getContainedContexts() {
        return containedContexts;
    }

    /**
     * Sets the value of the containedContexts property.
     * 
     * @param value
     *     allowed object is
     *     {@link TContexts }
     *     
     */
    public void setContainedContexts(TContexts value) {
        this.containedContexts = value;
    }

}
