<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="AutomatedWebServiceMainService" targetNamespace="http://service.cmp.spi.iaas.uni_stuttgart/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://service.cmp.spi.iaas.uni_stuttgart/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema">
  <import namespace="http://service.cmp.spi.iaas.uni_stuttgart/" schemaLocation="automatedwebservicemain_schema1.xsd"/>
</schema>
  </wsdl:types>
  <wsdl:message name="automate">
    <wsdl:part name="parameters" element="tns:automate">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="automateResponse">
    <wsdl:part name="parameters" element="tns:automateResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="AutomaticService">
    <wsdl:operation name="automate">
      <wsdl:input name="automate" message="tns:automate">
    </wsdl:input>
      <wsdl:output name="automateResponse" message="tns:automateResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="AutomatedWebServiceMainServiceSoapBinding" type="tns:AutomaticService">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="automate">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="automate">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="automateResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="AutomatedWebServiceMainService">
    <wsdl:port name="AutomaticServicePort" binding="tns:AutomatedWebServiceMainServiceSoapBinding">
      <soap:address location="http://localhost:8080/AutomatedDummyService/services"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
