//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.09 at 01:43:47 AM CET 
//


package unistuttgart.iaas.spi.cmprocess.processgen;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DefinitionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DefinitionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SensorClasses" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="AverageOperatorNeeded" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *       &lt;attribute name="definitionLanguage" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DefinitionType", propOrder = {
    "sensorClasses",
    "averageOperatorNeeded"
})
public class DefinitionType {

    @XmlElement(name = "SensorClasses")
    protected int sensorClasses;
    @XmlElement(name = "AverageOperatorNeeded")
    protected int averageOperatorNeeded;
    @XmlAttribute(name = "definitionLanguage")
    protected String definitionLanguage;

    /**
     * Gets the value of the sensorClasses property.
     * 
     */
    public int getSensorClasses() {
        return sensorClasses;
    }

    /**
     * Sets the value of the sensorClasses property.
     * 
     */
    public void setSensorClasses(int value) {
        this.sensorClasses = value;
    }

    /**
     * Gets the value of the averageOperatorNeeded property.
     * 
     */
    public int getAverageOperatorNeeded() {
        return averageOperatorNeeded;
    }

    /**
     * Sets the value of the averageOperatorNeeded property.
     * 
     */
    public void setAverageOperatorNeeded(int value) {
        this.averageOperatorNeeded = value;
    }

    /**
     * Gets the value of the definitionLanguage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefinitionLanguage() {
        return definitionLanguage;
    }

    /**
     * Sets the value of the definitionLanguage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefinitionLanguage(String value) {
        this.definitionLanguage = value;
    }

}
