//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.09 at 01:43:47 AM CET 
//


package unistuttgart.iaas.spi.cmprocess.processgen;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InitialContextType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InitialContextType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Documentation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Context" type="{}ContextType" maxOccurs="unbounded"/>
 *         &lt;element name="ContextRule" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InitialContextType", propOrder = {
    "documentation",
    "context",
    "contextRule"
})
public class InitialContextType {

    @XmlElement(name = "Documentation", required = true)
    protected String documentation;
    @XmlElement(name = "Context", required = true)
    protected List<ContextType> context;
    @XmlElement(name = "ContextRule", required = true)
    protected String contextRule;

    /**
     * Gets the value of the documentation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentation() {
        return documentation;
    }

    /**
     * Sets the value of the documentation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentation(String value) {
        this.documentation = value;
    }

    /**
     * Gets the value of the context property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the context property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContext().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContextType }
     * 
     * 
     */
    public List<ContextType> getContext() {
        if (context == null) {
            context = new ArrayList<ContextType>();
        }
        return this.context;
    }

    /**
     * Gets the value of the contextRule property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContextRule() {
        return contextRule;
    }

    /**
     * Sets the value of the contextRule property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContextRule(String value) {
        this.contextRule = value;
    }

}
