//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.09 at 01:43:47 AM CET 
//


package unistuttgart.iaas.spi.cmprocess.processgen;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the unistuttgart.iaas.spi.cmprocess.processgen package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ProcessRepos_QNAME = new QName("", "ProcessRepos");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: unistuttgart.iaas.spi.cmprocess.processgen
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ProcessReposType }
     * 
     */
    public ProcessReposType createProcessReposType() {
        return new ProcessReposType();
    }

    /**
     * Create an instance of {@link TProcessDefinitionType }
     * 
     */
    public TProcessDefinitionType createTProcessDefinitionType() {
        return new TProcessDefinitionType();
    }

    /**
     * Create an instance of {@link DefinitionType }
     * 
     */
    public DefinitionType createDefinitionType() {
        return new DefinitionType();
    }

    /**
     * Create an instance of {@link SubIntentionType }
     * 
     */
    public SubIntentionType createSubIntentionType() {
        return new SubIntentionType();
    }

    /**
     * Create an instance of {@link ContainedIntentionsType }
     * 
     */
    public ContainedIntentionsType createContainedIntentionsType() {
        return new ContainedIntentionsType();
    }

    /**
     * Create an instance of {@link ContextType }
     * 
     */
    public ContextType createContextType() {
        return new ContextType();
    }

    /**
     * Create an instance of {@link InitialContextType }
     * 
     */
    public InitialContextType createInitialContextType() {
        return new InitialContextType();
    }

    /**
     * Create an instance of {@link IntentionType }
     * 
     */
    public IntentionType createIntentionType() {
        return new IntentionType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProcessReposType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ProcessRepos")
    public JAXBElement<ProcessReposType> createProcessRepos(ProcessReposType value) {
        return new JAXBElement<ProcessReposType>(_ProcessRepos_QNAME, ProcessReposType.class, null, value);
    }

}
